services:
  wallet-rpc:
    container_name: wallet-rpc
    image: wallet-rpc:latest
    ports:
      - "8080:8080"
    volumes:
      - ./deploy/docker-compose/wallet-rpc.yaml:/app/etc/wallet.yaml
    restart: unless-stopped

  wallet-api:
    container_name: wallet-api
    image: wallet-api:latest
    ports:
      - "8888:8888"
    volumes:
      - ./deploy/docker-compose/wallet-api.yaml:/app/etc/wallet-api.yaml
    depends_on:
      - wallet-rpc
    restart: unless-stopped
