// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: wallet.proto

package server

import (
	"context"

	"wallet/service/wallet/rpc/internal/logic"
	"wallet/service/wallet/rpc/internal/svc"
	"wallet/service/wallet/rpc/pb/pb"
)

type WalletServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedWalletServer
}

func NewWalletServer(svcCtx *svc.ServiceContext) *WalletServer {
	return &WalletServer{
		svcCtx: svcCtx,
	}
}

func (s *WalletServer) CreateWallet(ctx context.Context, in *pb.CreateWalletReq) (*pb.CreateWalletResp, error) {
	l := logic.NewCreateWalletLogic(ctx, s.svcCtx)
	return l.CreateWallet(in)
}

func (s *WalletServer) GetWallet(ctx context.Context, in *pb.GetWalletReq) (*pb.GetWalletResp, error) {
	l := logic.NewGetWalletLogic(ctx, s.svcCtx)
	return l.GetWallet(in)
}

func (s *WalletServer) Transfer(ctx context.Context, in *pb.TransferReq) (*pb.TransferResp, error) {
	l := logic.NewTransferLogic(ctx, s.svcCtx)
	return l.Transfer(in)
}
