// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"wallet/service/wallet/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/wallets",
				Handler: CreateWalletHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/wallets/:walletId",
				Handler: GetWalletHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wallets/transfer",
				Handler: TransferHandler(serverCtx),
			},
		},
	)
}
