// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: wallet.proto

package wallet

import (
	"context"

	"wallet/service/wallet/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateWalletReq  = pb.CreateWalletReq
	CreateWalletResp = pb.CreateWalletResp
	GetWalletReq     = pb.GetWalletReq
	GetWalletResp    = pb.GetWalletResp
	TransferReq      = pb.TransferReq
	TransferResp     = pb.TransferResp

	Wallet interface {
		CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletResp, error)
		GetWallet(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetWalletResp, error)
		Transfer(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error)
	}

	defaultWallet struct {
		cli zrpc.Client
	}
)

func NewWallet(cli zrpc.Client) Wallet {
	return &defaultWallet{
		cli: cli,
	}
}

func (m *defaultWallet) CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletResp, error) {
	client := pb.NewWalletClient(m.cli.Conn())
	return client.CreateWallet(ctx, in, opts...)
}

func (m *defaultWallet) GetWallet(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetWalletResp, error) {
	client := pb.NewWalletClient(m.cli.Conn())
	return client.GetWallet(ctx, in, opts...)
}

func (m *defaultWallet) Transfer(ctx context.Context, in *TransferReq, opts ...grpc.CallOption) (*TransferResp, error) {
	client := pb.NewWalletClient(m.cli.Conn())
	return client.Transfer(ctx, in, opts...)
}
