// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type CreateWalletReq struct {
}

type CreateWalletResp struct {
	WalletId int64 `json:"walletId"`
	Balance  int64 `json:"balance"`
}

type GetWalletReq struct {
	WalletId int64 `path:"walletId"`
}

type GetWalletResp struct {
	WalletId int64 `json:"walletId"`
	Balance  int64 `json:"balance"`
}

type TransferReq struct {
	FromWalletId int64  `json:"fromWalletId"`
	ToWalletId   int64  `json:"toWalletId"`
	Amount       int64  `json:"amount"`
	Remark       string `json:"remark,optional"`
}

type TransferResp struct {
	TransferId              string `json:"transferId"`
	FromWalletId            int64  `json:"fromWalletId"`
	ToWalletId              int64  `json:"toWalletId"`
	Amount                  int64  `json:"amount"`
	Remark                  string `json:"remark"`
	FromWalletBalanceBefore int64  `json:"fromWalletBalanceBefore"`
	FromWalletBalanceAfter  int64  `json:"fromWalletBalanceAfter"`
	ToWalletBalanceBefore   int64  `json:"toWalletBalanceBefore"`
	ToWalletBalanceAfter    int64  `json:"toWalletBalanceAfter"`
}
