// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type CreateWalletReq struct {
	UserId   int64  `json:"userId"`
	Currency string `json:"currency"`
}

type CreateWalletResp struct {
	WalletId int64 `json:"walletId"`
	Balance  int64 `json:"balance"`
}

type GetWalletReq struct {
	WalletId int64 `path:"walletId"`
}

type GetWalletResp struct {
	WalletId int64  `json:"walletId"`
	Balance  int64  `json:"balance"`
	Currency string `json:"currency"`
}

type TransferReq struct {
	FromWalletId int64  `json:"fromWalletId"`
	ToWalletId   int64  `json:"toWalletId"`
	Amount       int64  `json:"amount"`
	Remark       string `json:"remark,optional"`
}

type TransferResp struct {
	TransferId string `json:"transferId"`
}
