// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: wallet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletReq) Reset() {
	*x = CreateWalletReq{}
	mi := &file_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletReq) ProtoMessage() {}

func (x *CreateWalletReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletReq.ProtoReflect.Descriptor instead.
func (*CreateWalletReq) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{0}
}

type CreateWalletResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      int64                  `protobuf:"varint,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResp) Reset() {
	*x = CreateWalletResp{}
	mi := &file_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResp) ProtoMessage() {}

func (x *CreateWalletResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResp.ProtoReflect.Descriptor instead.
func (*CreateWalletResp) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletResp) GetWalletId() int64 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *CreateWalletResp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetWalletReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      int64                  `protobuf:"varint,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletReq) Reset() {
	*x = GetWalletReq{}
	mi := &file_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletReq) ProtoMessage() {}

func (x *GetWalletReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletReq.ProtoReflect.Descriptor instead.
func (*GetWalletReq) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletReq) GetWalletId() int64 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

type GetWalletResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      int64                  `protobuf:"varint,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResp) Reset() {
	*x = GetWalletResp{}
	mi := &file_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResp) ProtoMessage() {}

func (x *GetWalletResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResp.ProtoReflect.Descriptor instead.
func (*GetWalletResp) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletResp) GetWalletId() int64 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *GetWalletResp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type TransferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromWalletId  int64                  `protobuf:"varint,1,opt,name=fromWalletId,proto3" json:"fromWalletId,omitempty"`
	ToWalletId    int64                  `protobuf:"varint,2,opt,name=toWalletId,proto3" json:"toWalletId,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReq) Reset() {
	*x = TransferReq{}
	mi := &file_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReq) ProtoMessage() {}

func (x *TransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReq.ProtoReflect.Descriptor instead.
func (*TransferReq) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *TransferReq) GetFromWalletId() int64 {
	if x != nil {
		return x.FromWalletId
	}
	return 0
}

func (x *TransferReq) GetToWalletId() int64 {
	if x != nil {
		return x.ToWalletId
	}
	return 0
}

func (x *TransferReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type TransferResp struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TransferId              string                 `protobuf:"bytes,1,opt,name=transferId,proto3" json:"transferId,omitempty"`
	FromWalletId            int64                  `protobuf:"varint,2,opt,name=fromWalletId,proto3" json:"fromWalletId,omitempty"`
	ToWalletId              int64                  `protobuf:"varint,3,opt,name=toWalletId,proto3" json:"toWalletId,omitempty"`
	Amount                  int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Remark                  string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	FromWalletBalanceBefore int64                  `protobuf:"varint,6,opt,name=fromWalletBalanceBefore,proto3" json:"fromWalletBalanceBefore,omitempty"`
	FromWalletBalanceAfter  int64                  `protobuf:"varint,7,opt,name=fromWalletBalanceAfter,proto3" json:"fromWalletBalanceAfter,omitempty"`
	ToWalletBalanceBefore   int64                  `protobuf:"varint,8,opt,name=toWalletBalanceBefore,proto3" json:"toWalletBalanceBefore,omitempty"`
	ToWalletBalanceAfter    int64                  `protobuf:"varint,9,opt,name=toWalletBalanceAfter,proto3" json:"toWalletBalanceAfter,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TransferResp) Reset() {
	*x = TransferResp{}
	mi := &file_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResp) ProtoMessage() {}

func (x *TransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResp.ProtoReflect.Descriptor instead.
func (*TransferResp) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *TransferResp) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferResp) GetFromWalletId() int64 {
	if x != nil {
		return x.FromWalletId
	}
	return 0
}

func (x *TransferResp) GetToWalletId() int64 {
	if x != nil {
		return x.ToWalletId
	}
	return 0
}

func (x *TransferResp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferResp) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *TransferResp) GetFromWalletBalanceBefore() int64 {
	if x != nil {
		return x.FromWalletBalanceBefore
	}
	return 0
}

func (x *TransferResp) GetFromWalletBalanceAfter() int64 {
	if x != nil {
		return x.FromWalletBalanceAfter
	}
	return 0
}

func (x *TransferResp) GetToWalletBalanceBefore() int64 {
	if x != nil {
		return x.ToWalletBalanceBefore
	}
	return 0
}

func (x *TransferResp) GetToWalletBalanceAfter() int64 {
	if x != nil {
		return x.ToWalletBalanceAfter
	}
	return 0
}

var File_wallet_proto protoreflect.FileDescriptor

const file_wallet_proto_rawDesc = "" +
	"\n" +
	"\fwallet.proto\x12\x06wallet\"\x11\n" +
	"\x0fCreateWalletReq\"H\n" +
	"\x10CreateWalletResp\x12\x1a\n" +
	"\bwalletId\x18\x01 \x01(\x03R\bwalletId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"*\n" +
	"\fGetWalletReq\x12\x1a\n" +
	"\bwalletId\x18\x01 \x01(\x03R\bwalletId\"K\n" +
	"\rGetWalletResp\x12\x1a\n" +
	"\bwalletId\x18\x01 \x01(\x03R\bwalletId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalanceJ\x04\b\x03\x10\x04\"\x81\x01\n" +
	"\vTransferReq\x12\"\n" +
	"\ffromWalletId\x18\x01 \x01(\x03R\ffromWalletId\x12\x1e\n" +
	"\n" +
	"toWalletId\x18\x02 \x01(\x03R\n" +
	"toWalletId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\"\xfe\x02\n" +
	"\fTransferResp\x12\x1e\n" +
	"\n" +
	"transferId\x18\x01 \x01(\tR\n" +
	"transferId\x12\"\n" +
	"\ffromWalletId\x18\x02 \x01(\x03R\ffromWalletId\x12\x1e\n" +
	"\n" +
	"toWalletId\x18\x03 \x01(\x03R\n" +
	"toWalletId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x128\n" +
	"\x17fromWalletBalanceBefore\x18\x06 \x01(\x03R\x17fromWalletBalanceBefore\x126\n" +
	"\x16fromWalletBalanceAfter\x18\a \x01(\x03R\x16fromWalletBalanceAfter\x124\n" +
	"\x15toWalletBalanceBefore\x18\b \x01(\x03R\x15toWalletBalanceBefore\x122\n" +
	"\x14toWalletBalanceAfter\x18\t \x01(\x03R\x14toWalletBalanceAfter2\xbc\x01\n" +
	"\x06Wallet\x12A\n" +
	"\fCreateWallet\x12\x17.wallet.CreateWalletReq\x1a\x18.wallet.CreateWalletResp\x128\n" +
	"\tGetWallet\x12\x14.wallet.GetWalletReq\x1a\x15.wallet.GetWalletResp\x125\n" +
	"\bTransfer\x12\x13.wallet.TransferReq\x1a\x14.wallet.TransferRespB\x06Z\x04./pbb\x06proto3"

var (
	file_wallet_proto_rawDescOnce sync.Once
	file_wallet_proto_rawDescData []byte
)

func file_wallet_proto_rawDescGZIP() []byte {
	file_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)))
	})
	return file_wallet_proto_rawDescData
}

var file_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wallet_proto_goTypes = []any{
	(*CreateWalletReq)(nil),  // 0: wallet.CreateWalletReq
	(*CreateWalletResp)(nil), // 1: wallet.CreateWalletResp
	(*GetWalletReq)(nil),     // 2: wallet.GetWalletReq
	(*GetWalletResp)(nil),    // 3: wallet.GetWalletResp
	(*TransferReq)(nil),      // 4: wallet.TransferReq
	(*TransferResp)(nil),     // 5: wallet.TransferResp
}
var file_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.Wallet.CreateWallet:input_type -> wallet.CreateWalletReq
	2, // 1: wallet.Wallet.GetWallet:input_type -> wallet.GetWalletReq
	4, // 2: wallet.Wallet.Transfer:input_type -> wallet.TransferReq
	1, // 3: wallet.Wallet.CreateWallet:output_type -> wallet.CreateWalletResp
	3, // 4: wallet.Wallet.GetWallet:output_type -> wallet.GetWalletResp
	5, // 5: wallet.Wallet.Transfer:output_type -> wallet.TransferResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wallet_proto_init() }
func file_wallet_proto_init() {
	if File_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_proto_msgTypes,
	}.Build()
	File_wallet_proto = out.File
	file_wallet_proto_goTypes = nil
	file_wallet_proto_depIdxs = nil
}
